### ISSUE TITLE
Unable to stream live data

### ISSUE THREAD

**Issue by geekow** [ghtorrent/ghtorrent.org#397]
Hi,

Since my ssh key has been added I'm trying to stream updates from GHTorrent but I don't succeed.

I've tryed with this ruby snipped and I've got no output, after one or two seconds the program just do a normal exit:

```
require 'bunny'

conn = Bunny.new(:host => '127.0.0.1', :port => 5672,
                 :username => 'streamer', :password => 'streamer')
conn.start
ch  = conn.create_channel
exchange = ch.topic('ght-streams', :durable => true)

q = ch.queue('myusername_queue', :auto_delete => true)

q.bind(exchange, :routing_key => 'evt.gist.*')
q.subscribe do |delivery_info, properties, payload|
  puts "#{delivery_info.routing_key}: #{payload}"
end
```

I've also tryed with this Python snippet but it is just stuck on start_consuming and the callback function has never been called:

```

import pika


def callback(ch, method, properties, body):
    print(" [x] Received %r" % body)

host='127.0.0.1'
port=5672
username='streamer'
password='streamer'

credentials = pika.PlainCredentials(username, password)
connection = pika.BlockingConnection(pika.ConnectionParameters(host=host, port=port, credentials=credentials))
channel = connection.channel()
exchange = channel.exchange_declare(exchange='ght-streams', exchange_type='topic', durable=True)
channel.queue_declare('geekow_queue', auto_delete=True)
channel.queue_bind(queue='geekow_queue', exchange='ght-streams', routing_key='evt.push.*')
channel.basic_consume(callback, queue='geekow_queue', no_ack=True)
channel.start_consuming()
```
I've been able to manually check that the connection to the server is open so I don't think it's a problem a connectivity problem (I've launched the following command: ssh -L 5672:streamer.ghtorrent.org:5672 ghtorrent@streamer.ghtorrent.org, like asked on ghtorrent.org)

Thanks in advance for you help

**Comment by ardumont** [comment]
Hello,

> Since my ssh key has been added I'm trying to stream updates from GHTorrent but I don't succeed.

I am in the same predicament:
- PR merged [1]
- ssh connection ok
```
$ ssh -vi ~/.ssh/id-rsa-swh-ghtorrent -L 2765:streamer.ghtorrent.org:5672 ghtorrent@streamer.ghtorrent.org
...
debug1: Authentication succeeded (publickey).
Authenticated to streamer.ghtorrent.org ([104.208.162.172]:22).
debug1: Local connections to LOCALHOST:2765 forwarded to remote address streamer.ghtorrent.org:5672
...
```
- Code does nothing but connect, then stops without any particular error

Also, something does happen on the ssh connection part when triggering the script (with `ssh -v` flag):
```
debug1: Connection to port 2765 forwarding to streamer.ghtorrent.org port 5672 requested.
debug1: channel 3: new [direct-tcpip]
debug1: channel 3: free: direct-tcpip: listening port 2765 for streamer.ghtorrent.org port 5672, connect from 127.0.0.1 port 58970 to 127.0.0.1 port 2765, nchannels 4

```

# Connectivity ok

Connectivity seems ok since trying other made-up rabbitmq credentials fails with connection failure (as expected).  So i suppose we can conclude the ssh connection, forwarding port, and the rabbitmq server are ok.

I'm using somewhat the same snippet at the original issue author @geekow (except for the queue name and the routing key `evt.*.*`). Using this to match the streaming documentation [2] and assert everything is good. 
Which, unfortunately is not so far ;)

# Naming is hard

To again respect the documentation, trying to make the queue unique by prefixing it with a username. 
I am wondering where that username is supposed to come from though as it's not detailed in the documentation.
To no avail, I tested the following:
- `swh_queue` (made up name, abbreviation of the organization below)
- `ardumont_queue` (my username as committer of the PR [1])
- `SoftwareHeritage_queue` (the organization name from where the PR [1] was coming from)

Do you have any hints as to something we did wrong here?

Any help would be greatly appreciated.

Thanks for your time.

[1] https://github.com/ghtorrent/ghtorrent.org/pull/437
[2] http://ghtorrent.org/streaming.html

Cheers,

**Comment by ardumont** [comment]
> I am wondering where that username is supposed to come from though as it's not detailed in the documentation.

I also tried 'swh-ghtorrent_queue' ('swh-ghtorrent' is the free form name used in the ssh public key's entry in the merged PR [1]).

[1] #437

**Comment by gousiosg** [comment]
@geekow and @ardumont Thanks for reporting this and sorry for taking so long to reply. It turned out to be an issue with the service that gets the events from MongoDB and publishes them to RabbitMQ. It is now started with `supervise` so hopefully it won't die again :-)

@ardumont wrt naming: The naming scheme is not strict.`prefix_queuename` for any value of `prefix_` works.

Can you please confirm it works?

**Comment by ardumont** [comment]
> @geekow and @ardumont Thanks for reporting this and sorry for taking so long to reply.

Thank you for your time.

> It turned out to be an issue with the service that gets the events from MongoDB and publishes them to RabbitMQ. It is now started with supervise so hopefully it won't die again :-)

Awesome!

> Can you please confirm it works?

It works (both the ruby and python3 snippets ;)

Again, thanks for your time and the fix.

Cheers,
