### ISSUE TITLE
Issues with id 0 in the data set

### ISSUE THREAD

**Issue by dspinellis** [ghtorrent/ghtorrent.org#456]
The `mysql-2018-01-01` data set contains a few issues with issue-id 0.  My understanding is that GitHub does not assign 0 as an issue number.  I report this in case there is an underlying bug in the collection or processing that causes such issues to appear.

```
MariaDB [ghtorrent]> select count(*) from issues where issue_id = 0; 
+----------+
| count(*) |
+----------+
|       47 |
+----------+
1 row in set (4.20 sec)
```

**Comment by gousiosg** [comment]
Thanks! I have done a quick investigation; it looks like all those issues where created in a period between 16 and 24 Feb, 2013. In my view, there was some issue with either GHTorrent or GitHub that was since resolved. Given that there are so few of them and that the time period that those appeared in so limited, I tend to believe that it was a temporary issue with the GitHub.
